# Generated by Django 3.1.1 on 2020-09-30 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('md5', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField()),
                ('hash', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('time', models.DateTimeField(verbose_name='request time')),
                ('response_code', models.PositiveIntegerField()),
                ('bytes', models.BigIntegerField()),
                ('ref', models.TextField()),
                ('app', models.TextField()),
                ('forwarded_for', models.TextField()),
                ('outer_request', models.BooleanField()),
                ('country', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('company', models.TextField(null=True)),
                ('gz_hash', models.TextField()),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.configname')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.file')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('dp_version', models.TextField()),
                ('files', models.ManyToManyField(to='stats.File')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.configname')),
            ],
        ),
    ]
