# Generated by Django 3.1.1 on 2021-06-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='dp_version',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='file_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='session_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
