# Generated by Django 3.1.2 on 2021-03-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='category',
            field=models.TextField(null=True),
        ),
    ]
